#ifndef BOARD_SCREEN_COMBO
#define BOARD_SCREEN_COMBO 510 // 13.3 inch six-color ePaper Screen(T133A01)
#endif

#ifndef USE_XIAO_EPAPER_DISPLAY_BOARD_EE02
#define USE_XIAO_EPAPER_DISPLAY_BOARD_EE02
#endif